name: _macro_builder
publish-to: none
description: >-
  Builds macros.
repository: https://github.com/dart-lang/macros/tree/master/pkgs/_macro_builder
resolution: workspace

environment:
  sdk: ^3.6.0-48.0.dev

dependencies:
  dart_model: any

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
