name: macros_workspace
environment:
  sdk: ^3.7.0-39.0.dev
dev_dependencies:
  dart_flutter_team_lints: ^3.1.0
publish_to: none
workspace:
  - goldens/foo
  - pkgs/_analyzer_cfe_macros
  - pkgs/_analyzer_macros
  - pkgs/_analyzer_macros/test/package_under_test
  - pkgs/_cfe_macros
  - pkgs/_cfe_macros/test/package_under_test
  - pkgs/_macro_builder
  - pkgs/_macro_client
  - pkgs/_macro_host
  - pkgs/_macro_runner
  - pkgs/_macro_server
  - pkgs/_macro_tool
  - pkgs/_macro_tool/test/package_under_test
  - pkgs/_test_macros
  - pkgs/dart_model
  - pkgs/macro
  - pkgs/macro_service
  - tool/benchmark_generator
  - tool/dart_model_generator

# Update by running: tool/set_sdk_version <git ref>
dependency_overrides:
  _fe_analyzer_shared:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/_fe_analyzer_shared
      ref: a8bee55e94979730890500026884afcf33e68f2f
  _js_interop_checks:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/_js_interop_checks
      ref: a8bee55e94979730890500026884afcf33e68f2f
  _macros:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/_macros
      ref: a8bee55e94979730890500026884afcf33e68f2f
  analysis_server:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/analysis_server
      ref: a8bee55e94979730890500026884afcf33e68f2f
  analyzer:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/analyzer
      ref: a8bee55e94979730890500026884afcf33e68f2f
  analyzer_plugin:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/analyzer_plugin
      ref: a8bee55e94979730890500026884afcf33e68f2f
  analyzer_utilities:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/analyzer_utilities
      ref: a8bee55e94979730890500026884afcf33e68f2f
  build_integration:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/build_integration
      ref: a8bee55e94979730890500026884afcf33e68f2f
  compiler:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/compiler
      ref: a8bee55e94979730890500026884afcf33e68f2f
  dart2js_info:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/dart2js_info
      ref: a8bee55e94979730890500026884afcf33e68f2f
  dart2wasm:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/dart2wasm
      ref: a8bee55e94979730890500026884afcf33e68f2f
  dev_compiler:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/dev_compiler
      ref: a8bee55e94979730890500026884afcf33e68f2f
  front_end:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/front_end
      ref: a8bee55e94979730890500026884afcf33e68f2f
  frontend_server:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/frontend_server
      ref: a8bee55e94979730890500026884afcf33e68f2f
  heap_snapshot:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/heap_snapshot
      ref: a8bee55e94979730890500026884afcf33e68f2f
  js_ast:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/js_ast
      ref: a8bee55e94979730890500026884afcf33e68f2f
  js_runtime:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/js_runtime
      ref: a8bee55e94979730890500026884afcf33e68f2f
  js_shared:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/js_shared
      ref: a8bee55e94979730890500026884afcf33e68f2f
  kernel:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/kernel
      ref: a8bee55e94979730890500026884afcf33e68f2f
  analysis_server_plugin:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/analysis_server_plugin
      ref: a8bee55e94979730890500026884afcf33e68f2f
  language_server_protocol:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: third_party/pkg/language_server_protocol
      ref: a8bee55e94979730890500026884afcf33e68f2f
  linter:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/linter
      ref: a8bee55e94979730890500026884afcf33e68f2f
  mmap:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/mmap
      ref: a8bee55e94979730890500026884afcf33e68f2f
  telemetry:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/telemetry
      ref: a8bee55e94979730890500026884afcf33e68f2f
  vm:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/vm
      ref: a8bee55e94979730890500026884afcf33e68f2f
  vm_service:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/vm_service
      ref: a8bee55e94979730890500026884afcf33e68f2f
  wasm_builder:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/wasm_builder
      ref: a8bee55e94979730890500026884afcf33e68f2f
