name: _cfe_macros
publish-to: none
description: Macro support for the CFE.
resolution: workspace

environment:
  sdk: ^3.6.0-114.0.dev

dependencies:
  _macro_host: any
  dart_model: any
  front_end: any
  macro_service: any
  macros: any

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  frontend_server: any
  path: ^1.9.0
  test: ^1.25.0
