name: _macro_runner
publish-to: none
description: >-
  Runs macros.
repository: https://github.com/dart-lang/macros/tree/master/pkgs/_macro_runner
resolution: workspace

environment:
  sdk: ^3.7.0-123.0.dev

dependencies:
  _macro_builder: any
  macro_service: any

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  dart_model: any
  test: ^1.25.0
