name: generate_dart_model
publish-to: none
resolution: workspace
environment:
  sdk: ^3.7.0-123.0.dev

dependencies:
  dart_model: any
  dart_style: any
  json_schema: ^5.1.7

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.25.7
