name: macro_service
version: 0.0.1-wip
description: >-
  Macro communication with the macro host.
repository: https://github.com/dart-lang/macros/tree/master/pkgs/macro_service
resolution: workspace

environment:
  sdk: ^3.6.0-300.0.dev

dependencies:
  async: ^2.11.0
  dart_model: any

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.25.0
