name: dart_model
version: 0.0.1-wip
description: >-
  Data model for information about Dart code, queries about Dart code and
  augmentations to Dart code. Serializable with a versioned JSON schema for
  use by macros, generators and other tools.
repository: https://github.com/dart-lang/macros/tree/master/pkgs/dart_model
resolution: workspace

environment:
  sdk: ^3.7.0-39.0.dev

dependencies:
  collection: ^1.19.0

dev_dependencies:
  benchmark_harness: ^2.2.2
  dart_flutter_team_lints: ^3.0.0
  test: ^1.25.0
