name: _test_macros
publish-to: none
description: >-
  Some test macros.
repository: https://github.com/dart-lang/macros/tree/master/pkgs/_test_macros
resolution: workspace

environment:
  sdk: ^3.6.0-48.0.dev

dependencies:
  dart_model: any

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.25.0
