name: _test_macros
publish-to: none
description: >-
  Some test macros.
repository: https://github.com/dart-lang/macros/tree/master/pkgs/_test_macros
resolution: workspace

environment:
  sdk: ^3.6.0-114.0.dev

dependencies:
  dart_model: any
  macro: any
  macro_service: any

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.25.0

# TODO(language/3728): use the real feature when there is one.
# macro lib/declare_x_macro.dart#DeclareX package:_test_macros/declare_x_macro.dart#DeclareXImplementation
# macro lib/query_class.dart#QueryClass package:_test_macros/query_class.dart#QueryClassImplementation
