name: _test_macros
publish-to: none
description: >-
  Some test macros.
repository: https://github.com/dart-lang/macros/tree/master/pkgs/_test_macros
resolution: workspace

environment:
  sdk: ^3.7.0-39.0.dev

dependencies:
  dart_model: any
  macro: any
  macro_service: any

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.25.0

# TODO(language/3728): use the real feature when there is one.
# macro lib/declare_x_macro.dart#DeclareX package:_test_macros/declare_x_macro.dart#DeclareXImplementation
# macro lib/json_codable.dart#JsonCodable package:_test_macros/json_codable.dart#JsonCodableImplementation
# macro lib/query_class.dart#QueryClass package:_test_macros/query_class.dart#QueryClassImplementation
# macro lib/literal_params.dart#LiteralParams package:_test_macros/literal_params.dart#LiteralParamsImplementation
