name: macro
version: 0.0.1-wip
description: >-
  For implementing a macro.
repository: https://github.com/dart-lang/macros/tree/master/pkgs/macro
resolution: workspace

environment:
  sdk: ^3.6.0-48.0.dev

dependencies:
  collection: ^1.19.0
  dart_model: ^0.0.1-wip
  macro_service: ^0.0.1-wip

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.25.0
