name: _macro_server
publish-to: none
description: >-
  Serves a `macro_service`.
repository: https://github.com/dart-lang/macros/tree/master/pkgs/_macro_server
resolution: workspace

environment:
  sdk: ^3.6.0-48.0.dev

dependencies:
  dart_model: any
  macro_service: any

dev_dependencies:
  _macro_client: any
  _test_macros: any
  dart_flutter_team_lints: ^3.0.0
  test: ^1.25.0
