name: _macro_host
publish-to: none
description: >-
  Hosts macros.
repository: https://github.com/dart-lang/macros/tree/master/pkgs/_macro_host
resolution: workspace

environment:
  sdk: ^3.6.0-48.0.dev

dependencies:
  _macro_builder: any
  _macro_runner: any
  _macro_server: any
  macro_service: any

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
