name: _macro_client
publish-to: none
description: >-
  Connects user macro code to a macro host.
repository: https://github.com/dart-lang/macros/tree/master/pkgs/_macro_client
resolution: workspace

environment:
  sdk: ^3.6.0-48.0.dev

dependencies:
  macro: any
  macro_service: any

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
