name: _analyzer_macros
publish-to: none
description: Macro support for the analyzer.
resolution: workspace

environment:
  sdk: ^3.7.0-157.0.dev

dependencies:
  _analyzer_cfe_macros: any
  _macro_host: any
  analysis_server: any
  analyzer: any
  dart_model: any
  macro_service: any
  macros: any

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  path: ^1.9.0
  test: ^1.25.0
