name: _analyzer_macros
publish-to: none
description: Macro support for the analyzer.
resolution: workspace

environment:
  sdk: ^3.6.0-114.0.dev

dev_dependencies:
  analyzer: any
  dart_flutter_team_lints: ^3.0.0
  macros: any
  test: ^1.25.0
